# branches to build
branches:
  only:
    - master
  except:
    - gh-pages

image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

# build cache to preserve files/folders between builds
cache:
  - node_modules # local npm modules

# scripts that run after cloning repository
install:
  - yarn # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

# to run your custom scripts instead of automatic tests
test_script:
  - yarn run lint && yarn notest

deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GH_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose